dependencies:
  build:
   - maven:3.5.4
   - java:11.0.8

build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install

ci:
  builds:
    - name: default
      build_target: default
